export const selectors = {
  burgerIngredient: "burger_ingredient_elem",
  modal: "modal",
  modalTitle: "modal_title",
  ingredientName: "ingredient_name",
  ingredientCalories: "ingredient_calories",
  ingredientProteins: "ingredient_proteins",
  ingredientFat: "ingredient_fat",
  ingredientCarbohydrates: "ingredient_carbohydrates",
  closeModal: "close_modal",
  constructorPage: "constructor_page",
  submitButton: "button_submit",
  orderNumber: "order_number",
  constructorBun: "constructor_bun",
};
